import { render, screen } from '@testing-library/react';
import AuthLayout, { metadata } from '@/app/(auth)/layout';

describe('AuthLayout コンポーネント', () => {
  it('子コンポーネントが正常にレンダリングされる', () => {
    render(
      <AuthLayout>
        <div data-testid="child">テストメッセージ</div>
      </AuthLayout>
    );
    expect(screen.getByTestId('child')).toHaveTextContent('テストメッセージ');
  });

  it('metadata が正しくエクスポートされている', () => {
    expect(metadata).toEqual({
      title: 'Next.js',
      description: 'Generated by Next.js',
    });
  });
});