name: CI

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

# GitHub APIへのアクセス権限を設定
permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

  # テストは今後実装予定
  # unit-tests:
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   ...

  # integration-tests:
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   ...
